name: API Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/src/**'
      - 'postman/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/src/**'
      - 'postman/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  newman-tests:
    name: Newman API Tests
    runs-on: ubuntu-latest
    
    services:
      # Add MongoDB service container
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongosh --eval "db.adminCommand('ping')"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci
      
      - name: Start backend server
        working-directory: ./backend
        run: |
          npm run build
          nohup npm start &
          sleep 10  # Give the server time to start
        env:
          NODE_ENV: test
          PORT: 3000
          MONGODB_URI: mongodb://localhost:27017/airvik_test
          JWT_SECRET: test_jwt_secret
          JWT_REFRESH_SECRET: test_refresh_secret
          EMAIL_FROM: test@example.com
          EMAIL_SERVICE: test
          EMAIL_USER: test
          EMAIL_PASSWORD: test
          FRONTEND_URL: http://localhost:3000
      
      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra
      
      - name: Run Newman tests
        working-directory: ./AirVik/postman
        run: |
          newman run ./user-registration-email-verification.postman_collection.json \
          -e ./user-registration-email-verification.postman_environment.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export ./newman-report.html
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: ./AirVik/postman/newman-report.html
          retention-days: 7
